# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from flashtensors.proto import (
    storage_pb2 as storage__pb2,
)

GRPC_GENERATED_VERSION = "1.71.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in storage_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class StorageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadModelAsync = channel.unary_unary(
            "/storage.Storage/LoadModelAsync",
            request_serializer=storage__pb2.LoadModelRequest.SerializeToString,
            response_deserializer=storage__pb2.LoadModelResponse.FromString,
            _registered_method=True,
        )
        self.ConfirmModel = channel.unary_unary(
            "/storage.Storage/ConfirmModel",
            request_serializer=storage__pb2.ConfirmModelRequest.SerializeToString,
            response_deserializer=storage__pb2.ConfirmModelResponse.FromString,
            _registered_method=True,
        )
        self.UnloadModel = channel.unary_unary(
            "/storage.Storage/UnloadModel",
            request_serializer=storage__pb2.UnloadModelRequest.SerializeToString,
            response_deserializer=storage__pb2.UnloadModelResponse.FromString,
            _registered_method=True,
        )
        self.ClearMem = channel.unary_unary(
            "/storage.Storage/ClearMem",
            request_serializer=storage__pb2.ClearMemRequest.SerializeToString,
            response_deserializer=storage__pb2.ClearMemResponse.FromString,
            _registered_method=True,
        )
        self.RegisterModel = channel.unary_unary(
            "/storage.Storage/RegisterModel",
            request_serializer=storage__pb2.RegisterModelRequest.SerializeToString,
            response_deserializer=storage__pb2.RegisterModelResponse.FromString,
            _registered_method=True,
        )
        self.GetServerConfig = channel.unary_unary(
            "/storage.Storage/GetServerConfig",
            request_serializer=storage__pb2.GetServerConfigRequest.SerializeToString,
            response_deserializer=storage__pb2.GetServerConfigResponse.FromString,
            _registered_method=True,
        )


class StorageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LoadModelAsync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ConfirmModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UnloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ClearMem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RegisterModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetServerConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_StorageServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "LoadModelAsync": grpc.unary_unary_rpc_method_handler(
            servicer.LoadModelAsync,
            request_deserializer=storage__pb2.LoadModelRequest.FromString,
            response_serializer=storage__pb2.LoadModelResponse.SerializeToString,
        ),
        "ConfirmModel": grpc.unary_unary_rpc_method_handler(
            servicer.ConfirmModel,
            request_deserializer=storage__pb2.ConfirmModelRequest.FromString,
            response_serializer=storage__pb2.ConfirmModelResponse.SerializeToString,
        ),
        "UnloadModel": grpc.unary_unary_rpc_method_handler(
            servicer.UnloadModel,
            request_deserializer=storage__pb2.UnloadModelRequest.FromString,
            response_serializer=storage__pb2.UnloadModelResponse.SerializeToString,
        ),
        "ClearMem": grpc.unary_unary_rpc_method_handler(
            servicer.ClearMem,
            request_deserializer=storage__pb2.ClearMemRequest.FromString,
            response_serializer=storage__pb2.ClearMemResponse.SerializeToString,
        ),
        "RegisterModel": grpc.unary_unary_rpc_method_handler(
            servicer.RegisterModel,
            request_deserializer=storage__pb2.RegisterModelRequest.FromString,
            response_serializer=storage__pb2.RegisterModelResponse.SerializeToString,
        ),
        "GetServerConfig": grpc.unary_unary_rpc_method_handler(
            servicer.GetServerConfig,
            request_deserializer=storage__pb2.GetServerConfigRequest.FromString,
            response_serializer=storage__pb2.GetServerConfigResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "storage.Storage", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("storage.Storage", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Storage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LoadModelAsync(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/storage.Storage/LoadModelAsync",
            storage__pb2.LoadModelRequest.SerializeToString,
            storage__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ConfirmModel(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/storage.Storage/ConfirmModel",
            storage__pb2.ConfirmModelRequest.SerializeToString,
            storage__pb2.ConfirmModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UnloadModel(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/storage.Storage/UnloadModel",
            storage__pb2.UnloadModelRequest.SerializeToString,
            storage__pb2.UnloadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ClearMem(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/storage.Storage/ClearMem",
            storage__pb2.ClearMemRequest.SerializeToString,
            storage__pb2.ClearMemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RegisterModel(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/storage.Storage/RegisterModel",
            storage__pb2.RegisterModelRequest.SerializeToString,
            storage__pb2.RegisterModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetServerConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/storage.Storage/GetServerConfig",
            storage__pb2.GetServerConfigRequest.SerializeToString,
            storage__pb2.GetServerConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
